# Generated by Django 4.2.16 on 2024-10-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lending',
            name='expected_return_date',
        ),
    ]
