# Generated by Django 4.2.16 on 2024-10-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lending_employee_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='actual_return_date',
            new_name='return_date',
        ),
    ]
